# Generated by Django 5.2.1 on 2025-05-09 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='action',
            field=models.CharField(choices=[('turn_on', 'Turn On'), ('turn_off', 'Turn Off')], default='turn_on', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.CharField(default='Mon', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='source',
            field=models.CharField(default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone'),
        ),
    ]
