# Generated by Django 5.2.3 on 2025-06-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_analytics_core_analyt_zone_id_11de12_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('gpio_pin', models.PositiveIntegerField(blank=True, help_text='أدخل رقم الدبوس فقط، مثلاً: 26.', null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lamps', to='core.zone')),
            ],
        ),
    ]
